import { ContentData, Language } from './types';
import { Bot, Code, Database, QrCode, Palette, Server, Layers } from 'lucide-react';

export const CONTENT: Record<Language, ContentData> = {
  vi: {
    nav: {
      home: 'Trang chủ',
      about: 'Về SGC',
      services: 'Dịch vụ',
      portfolio: 'Dự án',
      contact: 'Liên hệ',
    },
    hero: {
      title: 'Giải Pháp Công Nghệ & AI Đột Phá Cho Doanh Nghiệp',
      subtitle: 'SGC mang đến sức mạnh chuyển đổi số toàn diện: Từ hạ tầng WordPress tối ưu đến Trí tuệ nhân tạo tiên tiến.',
      ctaPrimary: 'Tư Vấn Miễn Phí',
      ctaSecondary: 'Xem Dịch Vụ',
      badge: 'Công Nghệ Tiên Phong 2025',
    },
    about: {
      title: 'Về SGC',
      missionTitle: 'Sứ Mệnh',
      missionDesc: 'Cung cấp các giải pháp công nghệ giá trị gia tăng trên Internet, giúp doanh nghiệp Việt Nam và toàn cầu tối ưu hóa vận hành và tăng trưởng doanh thu.',
      techTitle: 'Nền Tảng Công Nghệ',
      techDesc: 'Chúng tôi sở hữu đội ngũ chuyên gia về AI Generative, Cloud Computing và Web Security, cam kết chất lượng và bảo mật hàng đầu.',
    },
    services: {
      title: 'Hệ Sinh Thái Dịch Vụ',
      subtitle: 'Giải pháp toàn diện từ cơ sở hạ tầng đến ứng dụng thông minh',
      items: [
        {
          id: 'infra',
          title: 'Tên miền & Hạ tầng',
          description: 'Đăng ký tên miền .vn, Web Hosting tốc độ cao, Email doanh nghiệp (Google, cPanel).',
          icon: 'Server',
          features: ['Tên miền định danh', 'Cloud Hosting', 'Email Bảo Mật', 'SSL Certificate'],
        },
        {
          id: 'wordpress',
          title: 'WordPress & Phát triển Web',
          description: 'Thiết kế Website/Landing Page chuẩn SEO, tích hợp AI, bảo mật và bảo trì hệ thống.',
          icon: 'Code',
          features: ['Thiết kế UI/UX', 'Web App', 'Bảo mật Web', 'Tối ưu tốc độ'],
        },
        {
          id: 'ai',
          title: 'Giải pháp AI Doanh nghiệp',
          description: 'Chatbot thông minh, Trợ lý ảo AI riêng cho CEO, Tự động hóa quy trình.',
          icon: 'Bot',
          features: ['AI Chatbot', 'Trợ lý ảo cá nhân', 'Phân tích dữ liệu', 'Automation'],
        },
        {
          id: 'forms',
          title: 'Custom Form Automation',
          description: 'Xây dựng biểu mẫu đa năng, tự động hóa thu thập và xử lý dữ liệu doanh nghiệp.',
          icon: 'Palette',
          features: ['Form Logic phức tạp', 'Tích hợp Google Sheets', 'Thông báo tự động', 'Phân quyền truy cập'],
        },
        {
          id: 'qr',
          title: 'Dịch vụ QR Code',
          description: 'Tạo và quản lý QR Code chuyên nghiệp, QR biến động cho Marketing và thanh toán.',
          icon: 'QrCode',
          features: ['QR Biến động', 'QR Thương hiệu', 'Tracking Scan', 'Menu QR'],
        },
        {
          id: 'others',
          title: 'Dịch vụ khác',
          description: 'Sản xuất Media, Quay chụp sự kiện, và các giải pháp công nghệ tùy chỉnh khác.',
          icon: 'Layers',
          features: ['Media Production', 'Quay chụp sự kiện', 'Tư vấn giải pháp', 'Bảo trì hệ thống'],
        },
      ],
    },
    portfolio: {
      title: 'Dự Án Tiêu Biểu',
      subtitle: 'Minh chứng cho chất lượng và hiệu quả chuyển đổi số',
      items: [
        {
          id: 'p1',
          title: 'E-commerce AI Integration',
          category: 'WordPress & AI',
          description: 'Tích hợp gợi ý sản phẩm bằng AI cho chuỗi bán lẻ thời trang.',
          imageUrl: 'https://picsum.photos/600/400?random=1',
          result: 'Tăng 30% tỷ lệ chuyển đổi',
        },
        {
          id: 'p2',
          title: 'Smart QR Check-in',
          category: 'QR Code Solution',
          description: 'Hệ thống check-in sự kiện 5000 người bằng QR Code động.',
          imageUrl: 'https://picsum.photos/600/400?random=2',
          result: 'Giảm 90% thời gian chờ',
        },
        {
          id: 'p3',
          title: 'CEO Dashboard Assistant',
          category: 'AI Solutions',
          description: 'Trợ lý ảo tổng hợp báo cáo tài chính hàng ngày.',
          imageUrl: 'https://picsum.photos/600/400?random=3',
          result: 'Tiết kiệm 2 giờ/ngày',
        },
      ],
    },
    contact: {
      title: 'Liên Hệ Với Chúng Tôi',
      subtitle: 'Sẵn sàng tư vấn giải pháp phù hợp nhất cho doanh nghiệp của bạn',
      formName: 'Họ và tên',
      formEmail: 'Email doanh nghiệp',
      formPhone: 'Số điện thoại',
      formMessage: 'Nội dung cần tư vấn',
      submit: 'Gửi Yêu Cầu',
      address: 'Tòa nhà TechHub, Quận 1, TP. Hồ Chí Minh, Việt Nam',
    },
    footer: {
      copyright: '© 2025 SGC Technology. All rights reserved.',
      terms: 'Điều khoản sử dụng',
      privacy: 'Chính sách bảo mật',
    },
    thankYou: {
      title: 'Cảm ơn bạn!',
      message: 'Chúng tôi đã nhận được yêu cầu và sẽ liên hệ lại trong thời gian sớm nhất.',
      backHome: 'Về Trang Chủ',
    },
    aiWidget: {
      title: 'SGC AI Assistant',
      placeholder: 'Hỏi về dịch vụ của chúng tôi...',
      send: 'Gửi',
      disclaimer: 'AI có thể mắc lỗi. Vui lòng kiểm tra thông tin quan trọng.',
    }
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      portfolio: 'Portfolio',
      contact: 'Contact',
    },
    hero: {
      title: 'Breakthrough Tech & AI Solutions for Business',
      subtitle: 'SGC delivers comprehensive digital transformation power: From optimized WordPress infrastructure to advanced Artificial Intelligence.',
      ctaPrimary: 'Free Consultation',
      ctaSecondary: 'View Services',
      badge: 'Pioneering Tech 2025',
    },
    about: {
      title: 'About SGC',
      missionTitle: 'Our Mission',
      missionDesc: 'Providing internet value-added services to help Vietnamese and global businesses optimize operations and grow revenue.',
      techTitle: 'Technology Foundation',
      techDesc: 'We possess a team of experts in Generative AI, Cloud Computing, and Web Security, committed to top-tier quality.',
    },
    services: {
      title: 'Service Ecosystem',
      subtitle: 'Comprehensive solutions from infrastructure to intelligent applications',
      items: [
        {
          id: 'infra',
          title: 'Domain & Infrastructure',
          description: '.vn Domain registration, High-speed Web Hosting, Business Email (Google, cPanel).',
          icon: 'Server',
          features: ['Brand Domains', 'Cloud Hosting', 'Secure Email', 'SSL Certificate'],
        },
        {
          id: 'wordpress',
          title: 'WordPress & Web Dev',
          description: 'SEO-standard Website/Landing Page design, AI integration, Security, and Maintenance.',
          icon: 'Code',
          features: ['UI/UX Design', 'Web Apps', 'Web Security', 'Speed Optimization'],
        },
        {
          id: 'ai',
          title: 'Enterprise AI Solutions',
          description: 'Smart Chatbots, Private AI Assistants for CEOs, Process Automation.',
          icon: 'Bot',
          features: ['AI Chatbots', 'Personal Assistants', 'Data Analysis', 'Automation'],
        },
        {
          id: 'forms',
          title: 'Custom Form Automation',
          description: 'Building multi-purpose smart forms, automating data collection and business processing.',
          icon: 'Palette',
          features: ['Complex Form Logic', 'Google Sheets Integration', 'Auto Notifications', 'Access Control'],
        },
        {
          id: 'qr',
          title: 'QR Code Services',
          description: 'Professional QR generation and management, Dynamic QR for Marketing and payments.',
          icon: 'QrCode',
          features: ['Dynamic QR', 'Branded QR', 'Scan Tracking', 'QR Menus'],
        },
        {
          id: 'others',
          title: 'Other Services',
          description: 'Media Production, Event Photography, and other custom technology solutions.',
          icon: 'Layers',
          features: ['Media Production', 'Event Photography', 'Solution Consulting', 'System Maintenance'],
        },
      ],
    },
    portfolio: {
      title: 'Featured Projects',
      subtitle: 'Proof of quality and digital transformation efficiency',
      items: [
        {
          id: 'p1',
          title: 'E-commerce AI Integration',
          category: 'WordPress & AI',
          description: 'Product recommendation engine via AI for fashion retail chain.',
          imageUrl: 'https://picsum.photos/600/400?random=1',
          result: '30% Conversion Uplift',
        },
        {
          id: 'p2',
          title: 'Smart QR Check-in',
          category: 'QR Code Solution',
          description: '5000-attendee event check-in system via Dynamic QR.',
          imageUrl: 'https://picsum.photos/600/400?random=2',
          result: '90% Wait Time Reduction',
        },
        {
          id: 'p3',
          title: 'CEO Dashboard Assistant',
          category: 'AI Solutions',
          description: 'Virtual assistant summarizing daily financial reports.',
          imageUrl: 'https://picsum.photos/600/400?random=3',
          result: 'Saved 2 hours/day',
        },
      ],
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'Ready to advise on the best solution for your business',
      formName: 'Full Name',
      formEmail: 'Business Email',
      formPhone: 'Phone Number',
      formMessage: 'How can we help?',
      submit: 'Send Request',
      address: 'TechHub Building, District 1, Ho Chi Minh City, Vietnam',
    },
    footer: {
      copyright: '© 2025 SGC Technology. All rights reserved.',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
    },
    thankYou: {
      title: 'Thank You!',
      message: 'We have received your request and will contact you shortly.',
      backHome: 'Back to Home',
    },
    aiWidget: {
      title: 'SGC AI Assistant',
      placeholder: 'Ask about our services...',
      send: 'Send',
      disclaimer: 'AI can make mistakes. Please verify important info.',
    }
  },
};